# 基础镜像，使用nginx作为基础镜像
FROM nginx
# 作者信息
MAINTAINER course

# 挂载目录，将主机上的/home/course/projects/system-ui目录挂载到容器中
VOLUME /home/course/projects/system-ui
# 创建目录，如果目录不存在则创建
RUN mkdir -p /home/course/projects/system-ui
# 指定工作目录，设置工作目录为/home/course/projects/system-ui
WORKDIR /home/course/projects/system-ui
# 复制nginx配置文件到容器中的/etc/nginx/nginx.conf路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到容器中的/home/course/projects/system-ui路径
COPY ./html/dist /home/course/projects/system-ui