# 定义一个Kubernetes ConfigMap对象，用于存储MongoDB的配置文件
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config # ConfigMap的名称
  namespace: course-cloud # 命名空间
data:
  mongo.conf: |-
    # MongoDB配置文件示例
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
    net:
      bindIp: 0.0.0.0
      port: 27017
    processManagement:
      fork: true
      pidFilePath: /var/run/mongodb/mongod.pid
    replication:
      replSetName: rs0

---

# 定义一个Kubernetes Service对象，用于访问MongoDB服务
apiVersion: v1
kind: Service
metadata:
  name: mongo-service # Service的名称
  namespace: course-cloud # 命名空间
spec:
  selector:
    app: mongo # 用于选择Pod的标签
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017
  type: NodePort

---

# 定义一个Kubernetes Deployment对象，用于部署MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment # Deployment的名称
  namespace: course-cloud # 命名空间
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo # 用于匹配Pod的标签
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb-container # 容器名称
          image: mongo:latest # MongoDB镜像
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
            - name: mongo-config-volume
              mountPath: /etc/mongo.conf
              subPath: mongo.conf
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: course-mongo-pvc # 需要预先创建的PersistentVolumeClaim
        - name: mongo-config-volume
          configMap:
            name: mongo-config
